config/routes.rb
Rails.application.routes.draw do
  
  resources :addresses

  resources :clients

  resources :projects do
    member do
      get 'task_list'
    end
  end

  resources :tasks do
    member do
      patch :complete
    end
  end

  devise_for :users

  root 'projects#index'

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id           :integer          not null, primary key
#  task_name    :string(255)
#  task_type_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#  project_id   :integer
#  completed_at :datetime
#

class Task < ActiveRecord::Base
	# Assocations
	belongs_to :task_type
	belongs_to :project


	# Validation
	validates :task_type_id, :project_id, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :complete, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @address = Address.first
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to action: 'index', notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete
    @task.update(completed_at: Time.zone.now)
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task_name, :task_type_id, :project_id, :completed_at)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper

	def task_types
		{
			1 => "Check The Project Address",
			2 => "Ensure There Is A Client For This Project"
		}
	end

end

app/views/tasks/_form.html.erb
<section class="row">
  <div class="col-md-8">

    <%= form_for(@task, :html => {:class => 'form-horizontal'} ) do |f| %>
      <% if @task.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :project_id, class: "col-sm-4 control-label" %>
        <div class="col-sm-8">
          <%= f.collection_select :project_id, Project.all, :id, :name, {:prompt=>true}, {:class=>'form-control'} %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :task_type_id, class: "col-sm-4 control-label" %>
        <div class="col-sm-8">
          <%= f.collection_select :task_type_id, task_types, :first, :last, {:prompt=>true}, {:class=>'form-control'} %>
        </div>
      </div>
      <%= f.button "Save Task", class: "btn btn-success pull-right" %>
    <% end %>

</section>

app/views/tasks/_index_row.html.erb
<tr id="task-row-<%= task.id %>" class="<%= "animated fadeInLeft" if first_render %>" >

  <td>
    <%= link_to '', edit_task_path(task) %>
    <h4><%= task_types[task.task_type_id] %></h4>
  </td>

  <td>
    <h4>The <%= task.project.name %> Project</h4>
  </td>

  <td>
    <% if task.completed_at %>
      <h4>Task Completed: <%= task.completed_at.strftime("%A %B #{task.completed_at.day.ordinalize} %Y") %></h4>
    <% else %>
      <%= link_to 'Complete Now', complete_task_path(task), method: :patch, data: { disable_with: 'Completing...' }, remote: true, class: "btn btn-primary" %>
    <% end %>
  </td>

  <td>
    <div class="pull-right">
      <%= link_to 'Delete This Task', task, method: :delete, class: "btn btn-danger" %>
    </div>
  </td>

</tr>

app/views/tasks/complete.js.erb
$("#task-row-<%= @task.id %>").replaceWith(
	"<%= escape_javascript(render partial: 'index_row', locals: { task: @task, first_render: true } ) %>"
); 

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<% link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<%= render 'shared/navbar' %>

<section class="row">
  <div class="col-md-10">
    <h1>Here Are Some Tasks</h1>
  </div>
  <div class="col-md-2">
    <%= link_to 'Add A New Task', new_task_path, class: "btn btn-default btn-block" %>
  </div>
</section>

<section class="row">
  <div class="col-md-12">

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Task Name</th>
          <th colspan="3">Project</th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task| %>
         <%= render partial: 'index_row', locals: { task: task, first_render: false } %>
        <% end %>
      </tbody>
    </table>

  </div>
</section>

app/views/tasks/new.html.erb
<h1>Create A New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path, class: "btn btn-link" %>

app/views/tasks/show.html.erb
<%= render 'shared/navbar' %>

<p>
  <strong>Task name:</strong>
  <%= @task.task_name %>
</p>

<p>
  <strong>Task type:</strong>
  <%= @task.task_type_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>