config/routes.rb
Rails.application.routes.draw do
  
  resources :addresses

  resources :clients

  resources :projects do
    member do
      get 'task_list'
    end
  end

  resources :tasks do
    member do
      patch :complete
    end
  end

  devise_for :users

  root 'projects#index'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top <%= "animated fadeInDown" if current_page?(root_path) %>" role="navigation">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to root_path, class: "navbar-brand logo-icon" do %>
        <i class="fa fa-thumb-tack fa-lg <%= root_animation %>"></i>
      <% end %>

      <%= link_to root_path, class: "navbar-brand" do %>
       Taskmaster
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li class='<%= is_active('/projects') or is_active('/') %>'><%= link_to "Projects", projects_path %></li>
        <li class='<%= is_active('/tasks') %>'><%= link_to "Tasks", tasks_path %></li>
        <li class='<%= is_active('/clients') %>'><%= link_to "Clients", clients_path %></li>
        <li class='<%= is_active('/addresses') %>'><%= link_to "Addresses", addresses_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to current_user.username , edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>            
          <% else %>
            <li><%= button_to "Log In", new_user_session_path, class: "btn navbar-btn btn-primary" %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>  
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>