config/routes.rb
Rails.application.routes.draw do
  
  resources :addresses

  resources :clients

  resources :projects do
    member do
      get 'task_list'
    end
  end

  resources :tasks do
    member do
      patch :complete
    end
  end

  devise_for :users

  root 'projects#index'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  address_id :integer
#  client_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Project < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	belongs_to :address
	belongs_to :client
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:task_list, :show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1/task_list
  def task_list
    @tasks = Task.where(:project_id => @project.id, :completed_at => nil)
    @clients = Client.all
    @addresses = Address.all
    if !@project.tasks.first
      flash[:notice] = "No tasks exist for this project yet. Go to the tasks section and create one!"
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to action: 'index', notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to action: 'task_list', notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :address_id, :client_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address_id %><br>
    <%= f.number_field :address_id %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.number_field :client_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= render 'shared/navbar' %>

<h1>Editing Project</h1>

<%= render 'form' %>

<% link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= render 'shared/navbar' %>

<h1>Listing projects</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="2">Name</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td>
          <div class="btn-group">
            <%= link_to 'Show Task List', {:controller => "projects", :action => "task_list", :id => project.id }, class: "btn btn-primary" %>
            <%= link_to 'Edit This Project', edit_project_path(project), class: "btn btn-info" %>
            <%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path, class: "btn btn-success" %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @project.address_id %>
</p>

<p>
  <strong>Client:</strong>
  <%= @project.client_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/task_list.html.erb
<%= render 'shared/navbar' %>


<section class="row">
	<div class="col-md-12">
		<h1><%= "#{@tasks.count} #{"Task".pluralize(@tasks.count)}" %> Yet To Be Completed On The <%= @project.name %> Project</h1> 
	</div>
</section>

<section class="row">
	<div class="col-md-12">

		<% @tasks.each do |task| %>
			<div class="card">
				<h3><%= task_types[task.task_type_id] %></h3>
				<%= render "projects/task_type_specific_partials/task_type_#{task.task_type_id}" %>
			</div>
		<% end %>

	</div>
</section>

<section class="row">
	<div class="col-md-12">
			<div class="btn-group pull-right">
				<%= link_to "Go Back To List of Projects", projects_path, class: "btn btn-default" %>
			</div>
	</div>
</section>